project:
  type: website
  output-dir: docs

website:
  title: "John Severini"
  site-url: "https://johnseverini.com"
  description: "PhD Candidate in Political Science at Georgetown University."
  open-graph: true
  twitter-card: true
  image: "images/headshot.jpg"
  search: false
  favicon: images/js.png #
  navbar:
    background: dark
    title: "John Severini"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Research"
        href: research.qmd
      - text: "Data"
        href: data.qmd
      - text: "Policy Writing"
        href: policy-writing.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer:
    center: "Â© 2026 John Severini"
    background: "#2c2c2c"
    foreground: "#cccccc"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    page-layout: full
